apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-backend-image  # Replace with your actual backend image
        env:
        - name: MONGO_URI
          value: "mongodb://root:example@mongo:27017/mern?authSource=admin"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: backend
